# Generated by Django 3.2 on 2021-04-07 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210407_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='idUser',
            new_name='idRole',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userRole',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.role'),
            preserve_default=False,
        ),
    ]
