# Generated by Django 3.2 on 2021-04-07 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('idContract', models.AutoField(primary_key=True, serialize=False)),
                ('contractName', models.CharField(max_length=45)),
                ('limits', models.JSONField(null=True)),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('idEquipment', models.AutoField(primary_key=True, serialize=False)),
                ('equipName', models.CharField(max_length=255)),
                ('equipNum', models.CharField(max_length=255)),
                ('equipRange', models.CharField(max_length=255)),
                ('equipError', models.CharField(max_length=255)),
                ('equipDateCur', models.DateField()),
                ('equipDateNext', models.DateField()),
                ('equipDocNum', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудования',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('idTemplate', models.AutoField(primary_key=True, serialize=False)),
                ('templateName', models.CharField(max_length=45)),
                ('templatePath', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблоны',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('idReport', models.AutoField(primary_key=True, serialize=False)),
                ('reportYear', models.CharField(max_length=45)),
                ('reportData', models.JSONField()),
                ('reportWind', models.CharField(max_length=45)),
                ('reportWeather', models.CharField(max_length=45)),
                ('reportSoil', models.CharField(max_length=45)),
                ('reportTemp', models.CharField(max_length=45)),
                ('reportWeather3', models.CharField(max_length=45)),
                ('reportElVoltage', models.CharField(max_length=45)),
                ('reportElCableL', models.CharField(max_length=45)),
                ('reportElCableR', models.CharField(max_length=45)),
                ('reportElRope', models.CharField(max_length=45)),
                ('reportElBus', models.CharField(max_length=45)),
                ('reportEquipAms', models.JSONField()),
                ('reportPhotosRes', models.JSONField(null=True)),
                ('reportPDataAms', models.JSONField(null=True)),
                ('reportEquipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.equipment')),
                ('reportObject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='objects.object')),
                ('reportTemplate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.template')),
                ('reportUser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('idOperator', models.AutoField(primary_key=True, serialize=False)),
                ('operatorName', models.CharField(max_length=45)),
                ('operatorContract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.contract')),
                ('operatorReport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.report')),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблоны',
            },
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('idReport', 'reportEquipment'), name='unique_equipment'),
        ),
    ]
