# Generated by Django 3.2 on 2021-04-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_operator_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='idContract',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='idEquipment',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='idReport',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='idTemplate',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
