# Generated by Django 3.2 on 2021-04-11 12:06

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20210407_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reportDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='reportMeasuresDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
