# Generated by Django 3.2 on 2021-04-11 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_team'),
        ('reports', '0004_auto_20210411_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='reportUser',
        ),
        migrations.AddField(
            model_name='report',
            name='reportTeam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.team'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='equipment',
            table='reports_equipment',
        ),
    ]
