# Generated by Django 3.2 on 2021-04-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20210411_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reportEquipAms',
            field=models.JSONField(null=True),
        ),
    ]
