# Generated by Django 3.2 on 2021-04-14 14:42

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_report_reportequipams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reportEquipAms',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
