# Generated by Django 3.2 on 2021-04-15 08:08

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_auto_20210415_0808'),
        ('reports', '0007_alter_report_reportequipams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='operatorContract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.contract'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='operatorReport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reportEquipAms',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='reportEquipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.equipment'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reportObject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.object'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reportTemplate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.template'),
        ),
        migrations.AlterModelTable(
            name='report',
            table='reports_report',
        ),
    ]
