# Generated by Django 3.2 on 2021-05-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='equipError_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipError_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipName_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipName_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipRange_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipRange_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='reportSoil_en',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='reportSoil_ru',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='reportWeather_en',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='reportWeather_ru',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='reportWind_en',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='reportWind_ru',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
