# Generated by Django 3.2 on 2021-05-06 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_auto_20210504_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='equipError_en',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipError_ru',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipName_en',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipName_ru',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipRange_en',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipRange_ru',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reportSoil_en',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reportSoil_ru',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reportWeather_en',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reportWeather_ru',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reportWind_en',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reportWind_ru',
        ),
    ]
