# Generated by Django 3.2 on 2021-04-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='objAmsSection',
            field=models.CharField(choices=[('tower', 'Башня'), ('mast', 'Мачта'), ('roof_mast', 'Мачта на кровле'), ('pillar', 'Столб'), ('tripod', 'Трипод'), ('roof_monopole', 'Монополь (на кровле)')], default='Квадрат', max_length=15),
        ),
        migrations.AlterField(
            model_name='object',
            name='objAmsType',
            field=models.CharField(choices=[('square', 'Квадрат'), ('triangle', 'Треугольник'), ('circle', 'Круг')], default='Квадрат', max_length=8),
        ),
        migrations.DeleteModel(
            name='AmsType',
        ),
    ]
