# Generated by Django 3.2 on 2021-04-15 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_auto_20210411_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='objCity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.city'),
        ),
        migrations.AlterField(
            model_name='object',
            name='objCountry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.country'),
        ),
        migrations.AlterField(
            model_name='object',
            name='objRegion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.region'),
        ),
    ]
