# Generated by Django 3.2 on 2021-05-04 08:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_auto_20210415_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='amsDeviation',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Отклонение'),
        ),
        migrations.AlterField(
            model_name='object',
            name='amsDocsDev',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Разработчик проектной документации'),
        ),
        migrations.AlterField(
            model_name='object',
            name='amsFastenHeight',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Высота крепления'),
        ),
        migrations.AlterField(
            model_name='object',
            name='amsHeight',
            field=models.IntegerField(verbose_name='Высота АМС'),
        ),
        migrations.AlterField(
            model_name='object',
            name='amsImgEquip',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Схема расположения оборудования на Объекте'),
        ),
        migrations.AlterField(
            model_name='object',
            name='amsImgPhotos',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фотографии Объекта'),
        ),
        migrations.AlterField(
            model_name='object',
            name='amsImgPlan',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Схема Объекта'),
        ),
        migrations.AlterField(
            model_name='object',
            name='amsOperator',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наличие операторов связи на Объекте'),
        ),
        migrations.AlterField(
            model_name='object',
            name='amsProducer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Изготовитель Объекта'),
        ),
        migrations.AlterField(
            model_name='object',
            name='amsRopeDia',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Диаметр каната'),
        ),
        migrations.AlterField(
            model_name='object',
            name='amsRopesQty',
            field=models.IntegerField(verbose_name='Количество канатов'),
        ),
        migrations.AlterField(
            model_name='object',
            name='amsTension',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Натяжения'),
        ),
        migrations.AlterField(
            model_name='object',
            name='amsWaterproof',
            field=models.TextField(blank=True, null=True, verbose_name='Гидроизоляция'),
        ),
        migrations.AlterField(
            model_name='object',
            name='objAddress',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='object',
            name='objAmsSection',
            field=models.CharField(choices=[('tower', 'Башня'), ('mast', 'Мачта'), ('roof_mast', 'Мачта на кровле'), ('pillar', 'Столб'), ('tripod', 'Трипод'), ('roof_monopole', 'Монополь (на кровле)')], default='Квадрат', max_length=15, verbose_name='Тип секции'),
        ),
        migrations.AlterField(
            model_name='object',
            name='objAmsType',
            field=models.CharField(choices=[('square', 'Квадрат'), ('triangle', 'Треугольник'), ('circle', 'Круг')], default='Квадрат', max_length=8, verbose_name='Тип фермы'),
        ),
        migrations.AlterField(
            model_name='object',
            name='objCity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='object',
            name='objCountry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='object',
            name='objDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='АдДатарес'),
        ),
        migrations.AlterField(
            model_name='object',
            name='objFermType',
            field=models.CharField(choices=[('sq_ferm', 'ферма квадратная'), ('tr_ferm', 'ферма треугольная'), ('pipe', 'труба'), ('pillar', 'столб')], default='ферма квадратная', max_length=7, verbose_name='Тип фермы'),
        ),
        migrations.AlterField(
            model_name='object',
            name='objGeoLat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='object',
            name='objGeoLng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='object',
            name='objNote',
            field=models.TextField(verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='object',
            name='objNum',
            field=models.IntegerField(blank=True, null=True, verbose_name='Альтернативный код'),
        ),
        migrations.AlterField(
            model_name='object',
            name='objReg',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Шифр / код объекта'),
        ),
        migrations.AlterField(
            model_name='object',
            name='objRegion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='object',
            name='objStatus',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='object',
            name='sectionLength',
            field=models.IntegerField(verbose_name='Длина секции'),
        ),
        migrations.AlterField(
            model_name='object',
            name='signalSigns',
            field=models.BooleanField(default=True, verbose_name='Сигнальные огни'),
        ),
    ]
