# Generated by Django 3.2 on 2021-04-27 13:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_alter_customuser_userrole'),
        ('objects', '0003_auto_20210415_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('idOrder', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('orderDate', models.DateField(default=datetime.date.today)),
                ('orderAddress', models.CharField(max_length=100)),
                ('orderWorks', models.TextField(blank=True)),
                ('orderContacts', models.TextField(blank=True)),
                ('orderCodes', models.TextField(blank=True)),
                ('orderCity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.city')),
                ('orderCountry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.country')),
                ('orderObject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.object')),
                ('orderRegion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.region')),
                ('orderTeam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.team')),
            ],
            options={
                'verbose_name': 'Наряд',
                'verbose_name_plural': 'Наряды',
            },
        ),
    ]
