# Generated by Django 3.2 on 2021-05-04 08:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_auto_20210504_0852'),
        ('users', '0010_auto_20210504_0852'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderAddress',
            field=models.CharField(max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderCity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderCodes',
            field=models.TextField(blank=True, verbose_name='Коды работ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderContacts',
            field=models.TextField(blank=True, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderCountry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderDate',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderObject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.object', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderRegion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderTeam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.team', verbose_name='Бригада'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderWorks',
            field=models.TextField(blank=True, verbose_name='Работы на объекте'),
        ),
    ]
